version: "2"
services:
  db:
    container_name: mysql-springular-framework-itg
    image: mysql:5.7
    ports:
      - 4070:3306
    environment:
      MYSQL_ROOT_PASSWORD: sifast2014
      MYSQL_DATABASE: db_cho
    networks:
      app_net:
        ipv4_address: 10.0.70.2
  springular-framework-itg:
    container_name: springular-framework-itg
    build: .
    ports:
      - "8081:9090"
    networks:
      app_net:
        ipv4_address: 10.0.70.3
    depends_on:
      - db
    links:
      - db
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.70.0/24
          gateway: 10.0.70.1
