version: "2"
services:
  db:
    container_name: mysql-springular-framework-rec
    image: mysql:5.7
    ports:
      - 4071:3306
    environment:
      MYSQL_ROOT_PASSWORD: sifast2014
      MYSQL_DATABASE: db_cho
    networks:
      app_net:
        ipv4_address: 10.0.71.2
  springular-framework-rec:
    container_name: springular-framework-rec
    build: .
    ports:
      - "8071:9090"
    networks:
      app_net:
        ipv4_address: 10.0.71.3
    depends_on:
      - db
    links:
      - db
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.71.0/24
          gateway: 10.0.71.1
